title: "Assignment 05 - Literate Programming with Quarto"
author: "Lisa Blackmer-Raynolds"
date: "2025-06-04"
bibliography: references.bib

project:
  type: website
  output-dir: docs

website:
  title: "Assignment 05 - Literate Programming with Quarto"
  navbar:
    left:
      - href: table.qmd
        text: "Correlation Analysis"
      - about.qmd
  page-footer: "Built with Quarto by Lisa Blackmer-Raynolds"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    fig_caption: true
    self-contained: true



